M48
; DRILL file {KiCad (6.0.6)} date Sun Jul 17 10:27:17 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-17T10:27:17+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0340
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.1063
%
G90
G05
T1
X7.53Y-3.82
T2
X7.63Y-4.05
X7.83Y-4.05
T3
X7.58Y-3.4
X7.58Y-3.5
X7.58Y-3.6
X7.58Y-3.7
X7.88Y-3.4
X7.88Y-3.5
X7.88Y-3.6
X7.88Y-3.7
T4
X7.35Y-3.4616
X7.35Y-3.6584
X7.35Y-3.92
X7.35Y-4.1169
T0
M30
